version: "3.9"

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile.db
    container_name: simplepoll_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      DATABASE_HOST: database
      DATABASE_USER: simplepolluser
      DATABASE_PASSWORD: simplepollpass
      DATABASE_DB: simple_poll_db
    volumes:
      - db_data:/var/lib/mysql

  back-end:
    build: ./back-end
    container_name: my_backend
    environment:
      DATABASE_HOST: database
      DATABASE_USER: simplepolluser
      DATABASE_PASSWORD: simplepollpass
      DATABASE_DB: simple_poll_db
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"

  front-end:
    build: ./front-end
    container_name: my_frontend
    depends_on:
      - back-end
    ports:
      - "8080:80"

volumes:
  db_data: